### ISSUE TITLE
The Arweave Open Web Foundry

### ISSUE THREAD

**Issue by 0xKT** [WeLightProject/Arweave-Polygon-Bridge#15]
时间：
Feb 2nd, 2022 - March 17th, 2022

the Open Web Foundry offers:

- Deep Dives every Wednesday by industry experts on foundational topics
- Live support from profit sharing community experts on Discord, to answer questions
- Weekly ‘Community Spotlight’ events on Fridays
- helping you to refine your presentation skills before you pitch for investment.
- The programme culminates in Demo Day, an event allowing leading projects to showcase their work, and pitch for investment from the Arweave core team as well as supportive investors from throughout the Arweave ecosystem.

Successful submissions will meet the following criteria:

- Apps must be open source, with the full source code available on Github or another open code hosting repository. Feel free to use whatever OSS licence you prefer.
- Your project will ideally be a profit sharing community on Arweave. The owners of the associated profit sharing token receive royalties from usage of the app.
- By the end of the six-week programme, your project must include a link to a live, functioning, and running instance of the app itself, as well as a link to the repository it is stored within. It must also be published to ArweaveApps (see the submission process below).
- Your UI will ideally be hosted on Arweave.
- All applicants must join our Discord Dev server and share your submission in the #on-the-arweave channel upon completion.

Submission Deadline:

- 11:59pm EST on March 17th, 2022

Announcement Date:

- Investments will be announced after the end of the programme.

**Comment by leeduckgo** [comment]
to join the next round
