### ISSUE TITLE
[feat] how can I view the tx hash of uploading?

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Arweave-Polygon-Bridge#7]

**Comment by leeduckgo** [comment]
「这笔交易没有上链，也没有在交易池中」
↑ this func should be confirmed

**Comment by leeduckgo** [comment]
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/12784118/156100247-06309c3e-03a4-461c-a82d-e41f35b410bf.png">

> https://docs.bundlr.network/docs

Check document to see how can we got tx that sended by bundlr

**Comment by ErQi** [comment]
I can see the files by gateway:
```
https://sgc4o4sdak5xhiqa6nqxai6hkqnqaurllfealvykvrl62jhy.arweave.net/kYXH-ckMCu3O_i_APNhcCPHVBsAUitZSAXXCqxX7ST4
```
but I can not search it by node:
![image](https://user-images.githubusercontent.com/12586141/156358981-32d699af-df94-4e46-a574-30d58d133aea.png)

and I cant not search it in explorer:
![image](https://user-images.githubusercontent.com/12586141/156359071-d408db3e-24f6-4aef-8dbe-297df6176315.png)

**Comment by ErQi** [comment]
The second (node) route you most likely need to append `/data` - for viewblock, bundled transactions take a while to be indexed (multiple hours) - if you want something instant use the gateway's GQL

**Comment by leeduckgo** [comment]
above discussion from:
> https://github.com/Bundlr-Network/demo-app/issues/4
